### ISSUE TITLE
aes error 

### ISSUE THREAD

**Issue by reedalexandria** [reedalexandria/eds221-day9-activities#2]
``` r
library(tidyverse)

mtcars|>
  ggplot(aes(x = mpg, y = cyl)) +
  geom_point(aes(shape = 12), color = "purple") 
#> Error in `scale_f()`:
#> ! A continuous variable can not be mapped to shape
```

<sup>Created on 2022-08-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by reedalexandria** [comment]
``` r
mtcars|>
  ggplot(aes(x = mpg, y = cyl)) +
  geom_point(shape = 12, color = "purple") 
#> Error in ggplot(mtcars, aes(x = mpg, y = cyl)): could not find function "ggplot"
```

<sup>Created on 2022-08-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by michellelam777** [comment]
here it is again: 
library(tidyverse)

mtcars |> 
  ggplot(aes(x = mpg, y = cyl)) +
  geom_point(aes(shape = 12), color = "purple")

**Comment by michellelam777** [comment]
ignore previous post

**Comment by michellelam777** [comment]
``` r
library(tidyverse)

mtcars |> 
  ggplot(aes(x = mpg, y = cyl)) +
  geom_point(shape = 12, color = "purple")
```

![](https://i.imgur.com/xGs5fdV.png)

<sup>Created on 2022-08-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
